import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { MainLayout } from "@/layouts"
import "./globals.css"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
})

export const metadata: Metadata = {
	title: {
		template: "%s | fefade",
		default: "Blog | fefade"
	},
	description: "Generated by create next app",
	alternates: {
		canonical: "https://blog.fefade.com"
	}
}

export default function ({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-br">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	)
}
